DROP TABLE IF EXISTS TBL_EMPLOYEES, TBL_USER;

CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);


CREATE TABLE TBL_USER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  user_name VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL,
  active BIT DEFAULT NULL,
  roles VARCHAR (250) DEFAULT NULL
);

